### ISSUE TITLE
避免使用不常见的颜色名称

### ISSUE THREAD

**Issue by Wzb3422** [Vikiboss/easy-read#4]
https://github.com/Vikiboss/easy-read/blob/ecfbbab82eaa1b597fdf4809505ba322a73e2b67/src/pages/home/lists/lists.css#L41

尽量避免使用不常见的颜色名称 因为某些浏览器不支持
请使用 rgb / 十六进制 颜色代码

**Comment by Vikiboss** [comment]
ok
